#!/bin/bash -e

# Radicale for Synology DSM
#
# Copyright (C) 2017 Thomas Himmelstoss
#
# This software may be freely distributed under the MIT license. You should
# have received a copy of the MIT License along with this program.

VIRTUAL_ENV_URL="https://pypi.python.org/packages/d4/0c/9840c08189e030873387a73b90ada981885010dd9aea134d6de30cd24cb8/virtualenv-15.1.0.tar.gz"
VIRTUAL_ENV_MD5="44e19f4134906fe2d75124427dc9b716"

BUILD_DIR="${PWD}/build"
SRC_DIR="${PWD}/src"
PYTHON="$(which python3)"

# Reset the build directory
rm -rf "${BUILD_DIR}" && mkdir -p "${BUILD_DIR}/wheels"

# Download the virtualenv python package and check its MD5 value.
wget --no-check-certificate "--directory-prefix=${PWD}" "${VIRTUAL_ENV_URL}"

VIRTUAL_ENV_VERSION="$(ls "${PWD}"/virtualenv-*.tar.gz | awk 'match($0, /virtualenv-(.*).tar.gz/, v) {print v[1]}')"
echo "Version of virtualenv is: ${VIRTUAL_ENV_VERSION}"

DOWNLOAD_MD5="$(md5sum "${PWD}/virtualenv-${VIRTUAL_ENV_VERSION}.tar.gz" | awk '{print $1}')"

if [ "${VIRTUAL_ENV_MD5}" != "${DOWNLOAD_MD5}" ]; then
    echo "Hash of download doesn't match expected value"
    exit 1
fi

# Extract the tarball and move it to the build directory
tar -xvzf "${PWD}/virtualenv-${VIRTUAL_ENV_VERSION}.tar.gz"
mv "${PWD}/virtualenv-${VIRTUAL_ENV_VERSION}" "${BUILD_DIR}/virtualenv"

# Create a new python environment and install the required wheels.
${PYTHON} "${BUILD_DIR}/virtualenv/virtualenv.py" "${PWD}/build-env"

"${PWD}/build-env/bin/pip" wheel --wheel-dir "${BUILD_DIR}/wheels" "radicale==2.1.8"

cp "${PWD}/radicale.conf" "${BUILD_DIR}"
cp "${PWD}/radicale.users" "${BUILD_DIR}"
cp "${PWD}/logging.conf" "${BUILD_DIR}"

mkdir -p "${BUILD_DIR}/bin"
"${CC}" -std=c99 -o "${BUILD_DIR}/bin/pam_auth" -lpam "${SRC_DIR}/pam_auth.c"

