#!/bin/bash

# Radicale for Synology DSM
#
# Copyright (C) 2017 Thomas Himmelstoss
#
# This software may be freely distributed under the MIT license. You should
# have received a copy of the MIT License along with this program.

BUILD_DIR="${PWD}/build"
PKG_DIR="${PWD}/package_build"
PKG_DEST="/image/packages"

rm -rf "${PKG_DIR}" && mkdir -p "${PKG_DIR}"

mkdir -p "${PKG_DEST}"

source /pkgscripts/include/pkg_util.sh
source "${PWD}/build_vars.sh"

format_files() {
    for file in $*; do
        cp -av "${file}" "${file::-3}"
        sed -i "${file::-3}" \
	       -e "s/@@PKG_USER@@/${PKG_USER}/g" \
               -e "s/@@PKG_GROUP@@/${PKG_GROUP}/g" \
               -e "s/@@SHARE_NAME@@/${SHARE_NAME}/g"
    done
}

create_inner_tarball() {
    pkg_make_inner_tarball "${BUILD_DIR}" "${PKG_DIR}"
}

create_spk() {
    local scripts_dir="${PKG_DIR}/scripts"
    local conf_dir="${PKG_DIR}/conf"

    mkdir -vp "${scripts_dir}"
    mkdir -vp "${conf_dir}"

    cp -av scripts/* "${scripts_dir}"
    cp -av conf/* "${conf_dir}"

    format_files "${scripts_dir}"/*.in
    rm "${scripts_dir}"/*.in

    format_files "${conf_dir}"/*.in
    rm "${conf_dir}"/*.in

    # The code signing step expects a copy of the INFO file in the
    # project root directory which is the current working directory.
    "${PWD}/INFO.sh" > "${PWD}/INFO"
    cp -av "${PWD}/INFO" "${PKG_DIR}/INFO"

    pkg_make_spk "${PKG_DIR}" "${PKG_DEST}" $(pkg_get_spk_family_name)
}

create_inner_tarball
create_spk

