#!/bin/bash

# Radicale for Synology DSM
#
# Copyright (C) 2017 Thomas Himmelstoss
#
# This software may be freely distributed under the MIT license. You should
# have received a copy of the MIT License along with this program.

BUILD_DIR="${PWD}/build"
PKG_DIR="${PWD}/package_build"
PKG_DEST="${PWD}/packages"

rm -rf "${PKG_DIR}" && mkdir -p "${PKG_DIR}"

mkdir -p "${PKG_DEST}"

source /pkgscripts/include/pkg_util.sh

create_inner_tarball() {
    pkg_make_inner_tarball "${BUILD_DIR}" "${PKG_DIR}"
}

create_spk() {
    local scripts_dir="${PKG_DIR}/scripts"

    mkdir -p "${scripts_dir}"

    cp -av scripts/* "${scripts_dir}"

    ${PWD}/INFO.sh > "${PKG_DIR}/INFO"

    pkg_make_spk "${PKG_DIR}" "${PKG_DEST}" $(pkg_get_spk_family_name)
}

create_inner_tarball
create_spk

