#!/bin/bash

# Radicale for Synology DSM
#
# Copyright (C) 2017 Thomas Himmelstoss
#
# This software may be freely distributed under the MIT license. You should
# have received a copy of the MIT License along with this program.

PID_FILE="/tmp/radicale.pid"

log() {
    echo "[INFO] $1"
}

kill_active_servers() {
    log "Killing still active server processes"

    local pids="$(/bin/ps aux \
                  | grep 'python3.* -m radicale' \
		  | grep -v grep \
		  | awk '{print $2}')"

    for pid in ${pids}; do
        log "Terminating process with pid ${pid}"
	/bin/kill -TERM "${pid}"
    done
}

start_radicale() {
    kill_active_servers

    log "Starting Radicale"
    log "SYNOPKG_PKGDEST=${SYNOPKG_PKGDEST}"

    local python="${SYNOPKG_PKGDEST}/radicale-env/bin/python3"
    local pymodules="${SYNOPKG_PKGDEST}/lib"
    local configfile="${SYNOPKG_PKGDEST}/radicale.conf"

    log "python=${python}"
    log "pymodules=${pymodules}"
    log "configfile=${configfile}"

    PYTHONPATH="${pymodules}" "${python}" -m radicale --config "${configfile}"
}

stop_radicale() {
    log "Stopping Radicale"

    log "PID_FILE=${PID_FILE}"

    if [ -f "${PID_FILE}" ]; then
        local pid="$(cat ${PID_FILE})"

        log "Stopping process with pid ${pid}"

        /bin/kill -TERM "${pid}"
    else
        kill_active_servers
    fi

}

case $1 in
        start)
               start_radicale
	       exit 0
        ;;
        stop)
               stop_radicale
	       exit 0
	;;
        status)
	       exit 0
	;;
esac

