#!/bin/bash

# Radicale for Synology DSM
#
# Copyright (C) 2017 Thomas Himmelstoss
#
# This software may be freely distributed under the MIT license. You should
# have received a copy of the MIT License along with this program.

log() {
    echo "INFO: $1"
}

start_radicale() {
    log "Starting Radicale"
    log "SYNOPKG_PKGDEST=${SYNOPKG_PKGDEST}"
}

stop_radicale() {
    log "Stopping Radicale"
}

case $1 in
        start)
               start_radicale
	       exit 0
        ;;
        stop)
               stop_radicale
	       exit 0
	;;
        status)
	       exit 0
	;;
esac

